arb-dir: lib/l10n
template-arb-file: app_en.arb
output-class: AppLocalizations
output-localization-file: app_localizations.dart
output-dir: lib/l10n
synthetic-package: false
use-deferred-loading: false
untranslated-messages-file: untranslated_messages.txt