arb-dir: lib/l10n
template-arb-file: app_en.arb
output-class: AppLocalizations
synthetic-package: false
output-dir: lib/l10n
output-localization-file: app_localizations.dart
use-deferred-loading: false