name: av_wallet_hive
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  permission_handler: ^10.4.5
  logging: ^1.2.0
  http: ^1.1.0
  collection: ^1.18.0
  vector_math: ^2.1.4
  wifi_scan: ^0.4.1
  camera: ^0.10.5+9
  supabase_flutter: ^2.3.4
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  # ar_flutter_plugin:
  #   path: ./local_plugins/ar_flutter_plugin
  # flutter_unity_widget: ^2022.2.1  # Complètement supprimé

  google_sign_in: ^6.2.1
  noise_meter: ^5.0.2
  mic_stream: ^0.6.2
  share_plus: ^10.0.2
  csv: ^6.0.0
  pdf: ^3.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/logo.png
    - assets/background.jpg
    - assets/truss_icon.png
    - assets/flag_fr_48.png
    - assets/flag_en_48.png
    - assets/flag_it_48.png
    - assets/flag_de_48.png
    - assets/flag_es_48.png
    - assets/ru_drapeau.png
    - assets/structureicon.png
    - assets/truss_icon_grey.png
    - assets/icon_calculate_violet.png
    - assets/icon_calculate_blanc.png
    - assets/icons/truss_icon.png
    - assets/icons/tape_measure.png
    - assets/icon_faisceau_violet.png
    - assets/icon_faisceau_noir.png
    - assets/icon_faisceau_blanc.png
    - assets/images/
    - assets/corbeille/
    - assets/google_logo.png
    - assets/hotmail_logo.png
    - assets/apple_logo.png
    - assets/ar/
    - assets/ar/measure_start.glb
    - assets/ar/measure_end.glb
    - assets/ar/triangle.png
