name: av_wallet_hive
description: AV Wallet — Flutter app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # State / data
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # System / device
  permission_handler: ^10.4.5
  device_info_plus: ^9.1.1
  local_auth: ^2.1.6

  # Network / utils
  http: ^1.1.0
  logging: ^1.2.0
  collection: ^1.18.0
  crypto: ^3.0.3
  url_launcher: ^6.2.5
  url_strategy: ^0.2.0

  # Media / hardware
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  mic_stream: ^0.6.2
  noise_meter: ^5.0.2
  share_plus: ^10.0.2
  webview_flutter: ^4.4.2
  csv: ^6.0.0
  pdf: ^3.10.7
  vector_math: ^2.1.4
  wifi_scan: ^0.4.1

  # Auth / backend / payments
  supabase_flutter: ^2.3.4
  google_sign_in: ^6.2.1
  flutter_stripe: ^10.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/logo.png
    - assets/flag_fr_48.png
    - assets/flag_en_48.png
    - assets/flag_it_48.png
    - assets/flag_de_48.png
    - assets/flag_es_48.png
