// [L001]
import 'dart:io'; // [L002]
import 'package:flutter/material.dart'; // [L003]
import 'package:pdfx/pdfx.dart'; // [L004]
import 'package:open_filex/open_filex.dart'; // [L005]

class PdfPreviewTile extends StatelessWidget { // [L006]
  final String name; // [L007]
  final String path; // [L008]
  const PdfPreviewTile({super.key, required this.name, required this.path}); // [L009]

  @override
  Widget build(BuildContext context) { // [L010]
    return ListTile( // [L011]
      leading: const Icon(Icons.picture_as_pdf), // [L012]
      title: Text(name), // [L013]
      subtitle: Text(path, maxLines: 1, overflow: TextOverflow.ellipsis), // [L014]
      onTap: () async { // [L015]
        final file = File(path); // [L016]
        if (!await file.exists()) { // [L017]
          ScaffoldMessenger.of(context).showSnackBar( // [L018]
            const SnackBar(content: Text('Fichier introuvable')), // [L019]
          ); // [L020]
          return; // [L021]
        } // [L022]
        Navigator.of(context).push(MaterialPageRoute( // [L023]
          builder: (_) => _PdfViewerPage(title: name, filePath: path), // [L024]
        )); // [L025]
      }, // [L026]
      trailing: IconButton( // [L027]
        icon: const Icon(Icons.open_in_new), // [L028]
        onPressed: () => OpenFilex.open(path), // [L029]
      ), // [L030]
    ); // [L031]
  } // [L032]
} // [L033]

class _PdfViewerPage extends StatefulWidget { // [L034]
  final String title; // [L035]
  final String filePath; // [L036]
  const _PdfViewerPage({required this.title, required this.filePath}); // [L037]
  @override
  State<_PdfViewerPage> createState() => _PdfViewerPageState(); // [L038]
} // [L039]

class _PdfViewerPageState extends State<_PdfViewerPage> { // [L040]
  late PdfController _controller; // [L041]

  @override
  void initState() { // [L042]
    super.initState(); // [L043]
    _controller = PdfController( // [L044]
      document: PdfDocument.openFile(widget.filePath), // [L045]
      initialPage: 1, // [L046]
    ); // [L047]
  } // [L048]

  @override
  void dispose() { // [L049]
    _controller.dispose(); // [L050]
    super.dispose(); // [L051]
  } // [L052]

  @override
  Widget build(BuildContext context) { // [L053]
    return Scaffold( // [L054]
      appBar: AppBar(title: Text(widget.title)), // [L055]
      body: PdfView( // [L056]
        controller: _controller, // [L057]
        onDocumentLoaded: (_) { // [L058]
          debugPrint('PDF chargé: ${widget.filePath}'); // [L059]
        }, // [L060]
        onDocumentError: (e) { // [L061]
          debugPrint('Erreur PDF: $e'); // [L062]
          ScaffoldMessenger.of(context).showSnackBar( // [L063]
            SnackBar(content: Text('Erreur PDF: $e')), // [L064]
          ); // [L065]
        }, // [L066]
      ), // [L067]
    ); // [L068]
  } // [L069]
} // [L070]
